source 'https://rubygems.org'

gem "whiteboard", path: "../../whiteboard"
gem "persistence", path: "../persistence"
gem "sqlite3"
gem "slim-rails"

gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development do
  gem 'web-console', '~> 2.0'
end

